### ISSUE TITLE
No visitors.py in the maser branch?

### ISSUE THREAD

**Issue by liuhycs** [SMAT-Lab/Scalpel#123]
I am just curious whether you are refactoring the code, since visitors.py has been deleted in the typeinfer directory. 

BTW, where version is the stable version?

**Comment by Jarvx** [comment]
Hi, thank you for your interest.  Lots of refactoring is being made. So please feel free to open issues or make pull requests. Current main branch is mostly stable.

**Comment by Jarvx** [comment]
I will close this issue first.
