### ISSUE TITLE
Problem with typed-ast in analysers.py

### ISSUE THREAD

**Issue by matthiasmoke** [SMAT-Lab/Scalpel#19]
Hello,
similar to [a recent issue](https://github.com/SMAT-Lab/Scalpel/issues/18), I get an AttributeError (`module 'typed_ast' has no attribute '_ast3'`) when calling `infer_types()` of the `TypeInference` module.
My environment is Ubuntu 20.04 and Python version 3.8. I did dome digging and quickly found out that the typed-ast module does not support Python versions 3.8 and newer. (Mentioned in the [introduction on GitHub](https://github.com/python/typed_ast))
They recommend using the native `ast` library as the parser also supports type comments for the newer versions.
I just wanted to raise the issue again in case someone runs into similar problems. I will test the type inference with a lower version.

Edit: I tested versions 3.6.5 and 3.7.0, the error also occurs there

**Comment by billquan** [comment]
Hi,
Sorry we have fixed the issue but haven't merge it to the master branch, you can expect to see the fix very soon.
Thank you!

**Comment by billquan** [comment]
Hi,
We have merged the fix into the master branch, it should work now. Please use python 3.8 or higher when using the typeinfer module for now.
Type_ast doesn’t support parsing python 3.8+ but can be used in python 3.8+ to parse code in python version < 3.8.

**Comment by matthiasmoke** [comment]
Hey, the fix works :+1: 
Thank you very much!
