### ISSUE TITLE
Error while pip installing

### ISSUE THREAD

**Issue by tmfs10** [SMAT-Lab/Scalpel#21]
Hi,

When I try and run 'pip install Scalpel', I repeatedly get the error

`WARNING: Discarding https://files.pythonhosted.org/packages/66/46/bd7bbdf2a4a376c4c34288ddf45ca7779a0bd64c0e1aaf0952484634850f/scalpel-0.7.0.tar.gz#sha256=845c6b03de9b03a496718098deeea886b0e58b22608b172125257cfe8b40cdf6 (from https://pypi.org/simple/scalpel/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached scalpel-0.6.1.tar.gz (32 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ec2-user/anaconda3/envs/vector/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eoc0_wm0/scalpel_65cec16a055e471d90f4510e99e4b66c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eoc0_wm0/scalpel_65cec16a055e471d90f4510e99e4b66c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lhu2p5tv
       cwd: /tmp/pip-install-eoc0_wm0/scalpel_65cec16a055e471d90f4510e99e4b66c/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-eoc0_wm0/scalpel_65cec16a055e471d90f4510e99e4b66c/setup.py", line 4, in <module>
      import scalpel
    File "/tmp/pip-install-eoc0_wm0/scalpel_65cec16a055e471d90f4510e99e4b66c/scalpel/__init__.py", line 7, in <module>
      from constants import __version__
  ModuleNotFoundError: No module named 'constants'
  ----------------------------------------`

Installing from source doesn't work either

**Comment by Jarvx** [comment]
Thanks for pointing this out . The framework has not been uploaded to pip repository. So you need to install from the source, can you paste the output of installing from source.

**Comment by Jarvx** [comment]
Please feel free to reopen
