### ISSUE TITLE
Constant propagation for loop variables

### ISSUE THREAD

**Issue by simisimon** [SMAT-Lab/Scalpel#27]
Considering the following code.
```python
from sklearn.cluster import KMeans

for i in range(5):
    kmeans = KMeans(n_clusters=i)
```
I want to compute all possible value for the loop variable `i`. Using scalpel results into the following `const_dict`:
```
{('i', 0): None, ('kmeans', 0): <ast.Call object at 0x0000015FB8F6EC10>}
```
Is this behavior intentional? I would not expect `i` to be `None`. Instead, I would expect the `const_dict` to contain all the values `i` can have in the loop.

**Comment by simisimon** [comment]
Thank you. I'm looking to forward to the patch. I really like your tool, I'm using it in one of my projects.  :-)

**Comment by Jarvx** [comment]
Thanks for your kind words. It's great to know this!

**Comment by Jarvx** [comment]
> Hi, any updates when this problem will be fixed?

Thanks for the reminder. I am testing the feature now. Will push tomorrow at some time.

**Comment by Jarvx** [comment]
Now, I added support for the for-loop target, whose value is rewritten as the return value from next() of the iterator (e.g.  next(iter(range(10)))).  We will update the documentation next. Please feel free to reopen the issue if you see any runtime executions. Of course, any test cases are really appreciated.

**Comment by simisimon** [comment]
I looked into your provided fix and I do not know whether this should be the solution for this problem. 
https://github.com/SMAT-Lab/Scalpel/blob/2ba6cab3c7d613ed6e2dfe936f98b3b759a2347c/scalpel/SSA/const.py#L235-L242
The current solution creates two artifical ``ast.Call`` objects. I think this unnecessarily complicates constant propagation for loop variables. Instead, we should use the variable `iter_value` (which is a dead variable now), as this variable already contains the corresponding `ast.Call` object of the loop. Regarding the example above, `iter_value` would be the call of `range(5)`.

I would like to create an PR, but I do not have the permission. Therefore, I provide my suggested fix here:
```python
 if hasattr(stmt.target, "id"):    
     left_name = stmt.target.id 
     iter_value = stmt.iter 
     const_dict[left_name] = iter_value
```
or even better: 
```python
 if hasattr(stmt.target, "id"):    
     left_name = stmt.target.id 
     const_dict[left_name] = stmt-iter
```

**Comment by simisimon** [comment]
Corresponding test cases could look like:

```python
def test_in_range_loop():
    code_str = """for i in range(3):    x = i"""

    cfg = CFGBuilder().build_from_src(name="", src=code_str)

    _, const_dict = SSA().compute_SSA(cfg)
    
    assert const_dict
    assert len(const_dict) == 2
    assert isinstance(const_dict.get(('i', 0)), ast.Call) 
    assert isinstance(const_dict.get(('x', 0)), ast.Name)


def test_for_each_loop():
    code_str = """for x in y:    z = x"""

    cfg = CFGBuilder().build_from_src(name="", src=code_str)

    _, const_dict = SSA().compute_SSA(cfg)
    
    assert const_dict
    assert len(const_dict) == 2
    assert isinstance(const_dict.get(('x', 0)), ast.Call) 
    assert isinstance(const_dict.get(('z', 0)), ast.Name)
```
