### ISSUE TITLE
AttributeErrors caused by vars visitor

### ISSUE THREAD

**Issue by simisimon** [SMAT-Lab/Scalpel#29]
I found again several problems caused by the vars visitor module when analyzing ML projects. To reproduce the errors, run the following example:

```python
# AttributeError: 'int' object has no attribute '_fields'
code_str = """x = np.zeros(([Y.shape[0],X.shape[0]]))"""   

# AttributeError: 'Name' object has no attribute 'value'
# code_str = """z = np.array([x.test[i] for i in test])"""   

# AttributeError: 'Call' object has no attribute 'value'
# code_str = """best_tune = param_grid_list[tune_accs.index(max(tune_accs))]""" 

cfg = CFGBuilder().build_from_src(name="", src=code_str)

_, const_dict = SSA().compute_SSA(cfg)
```
Just change the `code_str` variable, to see the different errors. There are probably more errors. I try to add all the cases that I find.

If you need more information, just let me know.

**Comment by simisimon** [comment]
Here is a code string that causes another error:
```python
# AttributeError: 'str' object has no attribute '_fields'
code_str = """step['Model'] = model_name"""
````

**Comment by Jarvx** [comment]
> 

Thanks for raising this. Can you let me know your Python version as I could not reproduce this problem?

**Comment by simisimon** [comment]
I'm using Python 3.9.5.

**Comment by Jarvx** [comment]
The problem has now been fixed. This is due to syntax changes in the latest Python version. Thanks for offering this!.
