### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by khatchad** [SMAT-Lab/Scalpel#34]
In https://github.com/SMAT-Lab/Scalpel/wiki/Type-Inference#user-content-how-to-use-type-inference:
> The first parameter of `TypeInference` is the desired name for the inference analyzer, and the second one is the path to a python file or the root folder of a python package.

which is referring to:
```python
inferer = TypeInference(name='type_infer_example.py', entry_point='type_infer_example.py')
```
Isn't the first parameter the path to a Python file or the root folder of a python package and the second parameter an "entry point?" Are there multiple inference analyzers?

**Comment by Jarvx** [comment]
Hi, the first parameter is just the name for this inference. The second one can be either a source file path or a folder path (should not end with  '/')

We will clarify this in our documentation. Thanks for the question.

**Comment by khatchad** [comment]
Thank you for the clarification.
