### ISSUE TITLE
Constant propagation computes wrong values

### ISSUE THREAD

**Issue by simisimon** [SMAT-Lab/Scalpel#38]
Given the following test file, computing the constant values for `x` using scalpel results into a dictionary with three key-value pairs.

```python
x = "a"
x = "b"
x = 1
````

```python
with open("test_file.py", "r", encoding="utf-8") as source:
    code_str = source.read()

cfg = CFGBuilder().build_from_src(name="", src=code_str)

_, const_dict = SSA().compute_SSA(cfg)

print(const_dict)
````

````
{('x', 0): <ast.Constant object at 0x0000021BC9EFA430>, ('x', 1): <ast.Constant object at 0x0000021BC9EFA430>, ('x', 2): <ast.Constant object at 0x0000021BC9EFA430>}
````

That is what I expect. However, parsing the `ast.Constant` objects to get the actual values does not result into the correct values. Instead, I get the same value three times.
```python
 for key, value in const_dict.items():
        print(key, ast.unparse(value))
```
```
('x', 0) 1
('x', 1) 1
('x', 2) 1
```
This is not what I expect. Do you agree or am I missing something here?

**Comment by Jarvx** [comment]
It looks like a edge case. thanks for providing this test case

**Comment by Jarvx** [comment]
Thanks for raising this. The problem has now been fixed. It's indeed an edge case.
