### ISSUE TITLE
Import graph needs to be refactored and its current example code returning None

### ISSUE THREAD

**Issue by billquan** [SMAT-Lab/Scalpel#41]
As discussed in https://github.com/SMAT-Lab/Scalpel/issues/31#issuecomment-1140169998, [ImportGraph](https://github.com/SMAT-Lab/Scalpel/blob/87c8078148acaff98af7297c31801b959d019d27/scalpel/import_graph/import_graph.py#L33) needs to be refactored.
And the current tutorial code of it returns None, https://github.com/SMAT-Lab/Scalpel/blob/87c8078148acaff98af7297c31801b959d019d27/examples/import_graph_tutorial.py

**Comment by Jarvx** [comment]
The example code is updated using the latest API.
