### ISSUE TITLE
SSA class: Handling of tupels

### ISSUE THREAD

**Issue by mj-support** [SMAT-Lab/Scalpel#42]
Currently the SSA class is not able to detect assignment to variables in a tuple.
For example, if we want to detect the value of the variable "a" in the following code example, the SSA-class does not provide any result.

a, b = 1, 2

**Comment by Jarvx** [comment]
Hi @mj-support , thanks for raising this. if the tuple has the same number of elements as its right, then we can handle. Do you see some concrete example code from GitHub or somewhere? I mean can you offer some real-world example code snippets?
