### ISSUE TITLE
How powerful is scalpel in terms of handling ambiguity?

### ISSUE THREAD

**Issue by tristanlatr** [SMAT-Lab/Scalpel#44]
Hi, 

First thanks for building this tool, looks very helpful.

I’m one of the maintainers of [pydoctor](https://github.com/twisted/pydoctor), and I’m looking into this library in order to make our ast builder more powerful, especially in understanding complex `__all__` assignments and modifications. I have few questions.

Can scalpel infer list modifications? If so,
what is the inference of the `__all__` variable in such situations?

```python
__all__ = ['i',]
```

```python
from .mod import __all__ as a
import sys
__all__ = ['f', 'k']
if sys.version_info > (3,8):
    __all__.extend(a)
```

Does scalpel offer a way to consider version_info as if it takes a specified value and successful infer this without ambiguity?

Thanks

**Comment by Jarvx** [comment]
Hi,

I really appreciate your kind words.  First of all,  I would say with your case, if you want to evaluate runtime elements of __all__,  there is no API in this case that directly handle this.

But with existing APIs, I think it's possible for us to evaluate the value for __all__  without ambiguity cuz we provide flow-sensitive dataflow information.

**Comment by Jarvx** [comment]
Please feel free to reopen!  As this is an application of Scalpel project, I now close the issue.
