### ISSUE TITLE
Fix TypeErrors

### ISSUE THREAD

**Issue by tristanlatr** [SMAT-Lab/Scalpel#46]
Raising a string is not a thing in Python, these lines will trigger a TypeError.

![by default 2022-06-07 at 9 37 52 PM](https://user-images.githubusercontent.com/19967168/172512715-3d72d1df-1de6-4e8b-96f4-8e56391883b8.png)

Notice the difference:
```python
>>> raise ValueError()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError
>>> raise 'ValueError'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must derive from BaseException
```

Running `pytype` on this project to fix the obvious TypeErrors would be a good thing until you develop your own type checker ;)

**Comment by Jarvx** [comment]
Thanks for your kind help! Will fix soon!

**Comment by Jarvx** [comment]
The issue has been fixed now.
