### ISSUE TITLE
Add support to CFG construction when base class is same as derived class

### ISSUE THREAD

**Issue by Jarvx** [SMAT-Lab/Scalpel#50]
```Python
class A:
         def fun1():
               pass
Class A(A):
      def fun2():
            pass
```

**Comment by billquan** [comment]
This has been fixed. Currently, we only merge the class CFGs of class A and its base class if they share the same name, as we consider this as class A extending itself. 
The [base](https://github.com/SMAT-Lab/Scalpel/blob/634eee86e890d589bc8d403c3487b862cee92167/scalpel/cfg/builder.py#L246) could be an ast.Attribute, an ast.Call, or even an ast.Subscript, but currently we only consider the situation where it is an ast.Name.
