### ISSUE TITLE
"boolean" type not correctly recognized in <=python3.7

### ISSUE THREAD

**Issue by FrancoOu** [SMAT-Lab/Scalpel#64]

**Comment by Jarvx** [comment]
@FrancoOu  Can you attach traceback information here?

**Comment by FrancoOu** [comment]
> @FrancoOu Can you attach traceback information here?
![1658888766256](https://user-images.githubusercontent.com/64634122/181147165-927591ae-25b8-468d-b0ac-cac7512422ae.jpg)

**Comment by Jarvx** [comment]
Thanks for the information and your PR.
