### ISSUE TITLE
Constant Propagation: Variables that represent callables are not covered 

### ISSUE THREAD

**Issue by simisimon** [SMAT-Lab/Scalpel#67]
In the following example, a callable is passed as a variable to a parameter:

```python
def preprocessing(s):
    return s

v = TfidfVectorizer(analyzer=preprocessing)
````

Running Scalpel results into the following `const_dict`:
```
{('preprocessing', 0): None, ('v', 0): <ast.Call object at 0x0000016BCDE2AAC0>}
```

In this case, the function def should be assigned to the variable `preprocessing` instead if `None`.

**Comment by Jarvx** [comment]
Hi I am a bit confused, for a function name, what value do you think we should link  the name?

**Comment by simisimon** [comment]
I would expect that the `ast.FunctionDef` is assigned to the variable/callable `preprocessing`. So, the resulting const_dict would look like this: `{('preprocessing', 0): <ast.FunctionDef object at ..... >, ('v', 0): <ast.Call object at 0x0000016BCDE2AAC0>}`

**Comment by Jarvx** [comment]
Thanks, it looks you have implemented that. If possible, can you please create a PR?

**Comment by simisimon** [comment]
I already created a PR and I also linked it to this issue here.

**Comment by Jarvx** [comment]
> I already created a PR and I also linked it to this issue here.

Thanks for your contribution!
