### ISSUE TITLE
The last PR #70 removed my changes

### ISSUE THREAD

**Issue by simisimon** [SMAT-Lab/Scalpel#71]
Hi, I just wanted to work on #42 and create a PR for this issue. However, I noticed that my changes from PR #68 and #69 are not in the main branch anymore. I found out that the last PR #70 removed my changes. Is this intended?

**Comment by Jarvx** [comment]
This is not intended. It looks like some misoperations... I will try to figure out soon. 

Please feel free to tell anything !!!! thanks !

**Comment by Jarvx** [comment]
@simisimon  For #68 and #69 Can you please create new PRs as that will make it easier. Our team is really busy at the moment, so did not do well in managing PRs.  Sorry for this

**Comment by Jarvx** [comment]
We will later carefully follow steps to review every change.

**Comment by Jarvx** [comment]
@simisimon  I will manually recover this  issue during this weekend. Already make changes to the main branch. Thanks for pointing this out!

**Comment by simisimon** [comment]
No problem. I will create new PR's.
