### ISSUE TITLE
Readthedocs setup

### ISSUE THREAD

**Issue by tristanlatr** [SMAT-Lab/Scalpel#78]
Hi, here is the guide you need to follow to publish the Sphinx docs: https://docs.readthedocs.io/en/stable/tutorial/

EDIT: Just installing the webhook should be enough, I'll take care of the rest. 

then the link in the readme needs to be adjusted.

**Comment by Jarvx** [comment]
@tristanlatr  Thanks for your instructions in the email. Now the webhook  has been created

**Comment by Jarvx** [comment]
I now close this issue but will  give regular attention to the readdocs work.  Thanks for the great help!
