### ISSUE TITLE
PyPI distribution

### ISSUE THREAD

**Issue by git-afsantos** [SMAT-Lab/Scalpel#79]
Hello!

First of all, thank you for the work you have put into this project. I was starting to build my own, but I am glad that I found Scalpel.

I want to integrate Scalpel within my project, but with only a source installation, it is hard to manage dependencies, and I would rather not ship Scalpel's code within my project.

Are you planning on releasing this project via PyPI?
If so, considering that there are already a few (unrelated) projects using the same name, I would suggest naming this distribution `code-scalpel`, `python-scalpel`, `static-scalpel`, or something along those lines.

**Comment by git-afsantos** [comment]
For additional context, I test and build my projects using `tox` and virtual environments, following [this template](https://github.com/git-afsantos/bake-a-py).

**Comment by Jarvx** [comment]
thanks for your kind suggestion. A good name might be python-scalpel. 
Yes, I can say we will make it to PyPI next. The Scalpel project will have a major release next month, and then will be hosted on PyPI.

**Comment by Jarvx** [comment]
@git-afsantos   This is just a followup note. We have started building PyPI distribution.

**Comment by git-afsantos** [comment]
Thank you for letting me know!

**Comment by git-afsantos** [comment]
Sorry to bring this up again, @Jarvx , but I still cannot find this project on PyPI. Under which name is it hosted?
