### ISSUE TITLE
Remove the wiki and say the docs are on readthedocs

### ISSUE THREAD

**Issue by tristanlatr** [SMAT-Lab/Scalpel#88]
It can be confusing to have both the wiki and readthedocs setup. 

Also since the wiki is editable publicly (#32) some content might have been updated and the doc needs to be adjusted.

**Comment by Jarvx** [comment]
Wiki is unselected now, thanks !

**Comment by Jarvx** [comment]
Thanks for the reminder. 
No significant change has been made so far. We have the backups for wiki pages.  I will also try to merge everything to readdocs this month. I hope this is a concise way to handle it.
