### ISSUE TITLE
Fix packaging

### ISSUE THREAD

**Issue by tristanlatr** [SMAT-Lab/Scalpel#93]
Hello, 

Looks like there is a syntax error in the pyproject.toml, this fails the documentation build with error

`pip._vendor.tomli.TOMLDecodeError: Unclosed array (at line 7, column 21)`

You can even see the issue in github:

![Capture d’écran, le 2023-02-16 à 13 02 55](https://user-images.githubusercontent.com/19967168/219449892-8cb9a92e-65f4-4dc5-91ae-8241c1c6792b.png)

Also it seems that both setup.py and pyproject.toml are used to provide package information and metadata, this is an inconsistent setup. Either the pyproject.toml file should be removed or the setup.py should only contain a simple `setup()` call without any arguments.

**Comment by Jarvx** [comment]
Thank you for pointing this out. I have fixed it.
