### ISSUE TITLE
Cannot install in local to develop

### ISSUE THREAD

**Issue by samuelchassot** [SMAT-Lab/Scalpel#99]
Hi,
I wanted to work on the bug I found and exposed in #98 but I sadly cannot install the package locally using the command `python3 -m pip install -e .` as the Github Actions workflow file is suggesting. I also try to run the CI on a fork of the repo but the same error occured (i.e., the package `scalpel` is not found when importing).
I also try to simply install it locally (without the `-e` option) but it does not work. It is install under the `Scalpel` name with version `0.0.1` (as stated in `pyproject.toml` and thus different from `setup.py`)

Do you have any input on that? How are you testing the tool locally?

Thanks a lot!

**Comment by Jarvx** [comment]
Hi,

A simple way is Just cloning the project, use the scalpel folder only, and importing. 

---Scapel
         | - --- src
                     |- scaple
                     |- your script here. 

We changed the folder structure because we will follow the new packing guideline.

**Comment by samuelchassot** [comment]
Hi @Jarvx ,
Thanks for your quick reply! I just tried this solution but I still get this error:
```
  File ".../Scalpel/src/scalpel/test_cfg.py", line 2, in <module>
    from scalpel.cfg import CFGBuilder
ModuleNotFoundError: No module named 'scalpel'
```

**Comment by Jarvx** [comment]
> Hi @Jarvx , Thanks for your quick reply! I just tried this solution but I still get this error:
> 
> ```
>   File ".../Scalpel/src/scalpel/test_cfg.py", line 2, in <module>
>     from scalpel.cfg import CFGBuilder
> ModuleNotFoundError: No module named 'scalpel'
> ```

your test_cfg.py should appear under  src folder.

**Comment by Jarvx** [comment]
No problem!
